services:
  product-service:
    build:
      context: .
      dockerfile: product-service/Dockerfile
    container_name: product-service
    ports:
      - "8001:8001"
    volumes:
      - ./settings.toml:/product-service/settings.toml
    networks:
      - internal
    restart: always
    depends_on:
      - postgres

  order-service:
    build:
      context: .
      dockerfile: order-service/Dockerfile
    container_name: order-service
    ports:
      - "8002:8002"
    volumes:
      - ./settings.toml:/order-service/settings.toml
    networks:
      - internal
    restart: always
    depends_on:
      - postgres
      - product-service

  postgres:
      image: postgres
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_PASSWORD=mypassword
      networks:
        - internal
      restart: always

networks:
  internal:
    driver: bridge