[product_service_settings]
app_port = 8001
app_version = "1.0.0"
app_name = "product-service"
app_host = "127.0.0.1"
app_mount = "/api/v1"


[db_settings]
db_name = "postgres"
db_user = "postgres"
db_password = "mypassword"
db_host = "localhost"
db_port = 5432